version: '2.1'
services:
  demo:
    labels:
     - "is_top_app=0"
     - "description=Management front-end and back-end (simulated back-end management scripts)"
#    build: .
    image: hilbert/mng:devel_new # devel # ${IMAGE_VERSION:-latest}
    network_mode: host
    privileged: false
    stdin_open: false
    tty: false
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - "${HILBERT_SERVER_CONFIG_SSH_PATH:-~/.ssh}:/root/SSH:ro"
     - /tmp:/tmp:rw
     - "${HILBERT_SERVER_CONFIG_PATH:-./}:/HILBERT:ro"
    environment:
     - HOME=/root
#     - HILBERT_CLI_PATH=/usr/local/bin
     - HILBERT_SERVER_CONFIG_PATH=/HILBERT/
     - HILBERT_SERVER_CONFIG_SSH_PATH=/root/SSH
     - HILBERT_UI_SIMULATION_MODE=1
     - HILBERT_UI_INT_PORT=4444
     - HILBERT_UI_LOG_LEVEL=debug
     - HILBERT_UI_LOG_DIR=/var/log
     - HILBERT_UI_DB=""
     - HILBERT_UI_EXT_PORT=${HILBERT_UI_PORT:-8008}
    entrypoint:
     - /sbin/my_init
     - --skip-runit
     - --skip-startup-files
     - --
#    ports:
#     - "8888:8000"
    expose:
     - ${HILBERT_UI_PORT:-8008}
    restart: always
    command:
     - /usr/local/run.sh




  mng:
    extends: 
      service: demo
    labels:
     - "description=Management front-end and back-end (real management scripts)"
    restart: on-failure:5
    environment:
     - HILBERT_UI_SIMULATION_MODE=0
     - HILBERT_UI_INT_PORT=4444
     - HILBERT_UI_LOG_LEVEL=info
     - HILBERT_UI_DB=/HILBERT_DB/hilbert-dev.sqlite
    volumes:
     - "${HILBERT_UI_DB:-/tmp}:/HILBERT_DB:rw"
    command:
     - /usr/local/run.sh

